### ISSUE TITLE
new theme not visible on LM V3

### ISSUE THREAD

**Issue by adoeller** [TapioOfTapiola/oam_theme_tapiola#11]
![Screenshot_2024-06-30-21-53-21-187_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/1b536966-adb3-4662-b397-fa3877b8d83a)

**Comment by TapioOfTapiola** [comment]
Aww *** this again, will investigate.

**Comment by TapioOfTapiola** [comment]
Did 1.4.2 work for you?

**Comment by adoeller** [comment]
Yes, it does. The plain  released version and my modified version where I replaced the metro icon with a smaller one.

**Comment by TapioOfTapiola** [comment]
I found the error, please try the latest xml and report back, thx

**Comment by adoeller** [comment]
Works
