### ISSUE TITLE
issue on release 1.4.4

### ISSUE THREAD

**Issue by nono303** [TapioOfTapiola/oam_theme_tapiola#12]
Hi @TapioOfTapiola 
There is an issue on your new 1.4.4 release :
- https://github.com/TapioOfTapiola/oam_theme_tapiola/releases/download/Tapiola_v1.4.4/Tapiola.zip contain the new files but didn't correspond to any commit / tag on your main branch
- https://github.com/TapioOfTapiola/oam_theme_tapiola/archive/refs/tags/Tapiola_v1.4.4.zip contain `Tapiola 1.4.3d - 2024-07-24` commit https://github.com/TapioOfTapiola/oam_theme_tapiola/commit/dca7d1af16e662ed8a4533867b0b4ee734bb0db0

**Comment by TapioOfTapiola** [comment]
Sorry, didn't notice your report, need to check my notifications.
You're right.

- set 1.4.4 to "latest"
- uploaded Tapiola.xml
