### ISSUE TITLE
Zoomlevel 15+ blocks details available in level up to 14

### ISSUE THREAD

**Issue by adoeller** [TapioOfTapiola/oam_theme_tapiola#2]
![Screenshot_2023-10-06-10-21-02-149_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/6240fd92-feca-4382-8275-018b0390c4ae)
![Screenshot_2023-10-06-10-21-07-930_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/ea7b6238-8f16-4e46-8d6d-6abe23b0d9ec)

**Comment by adoeller** [comment]
![grafik](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/99a9bd76-e838-440e-87be-41842bad9708)

<area fill="#15F0DCD8" />
did solve the problem

**Comment by TapioOfTapiola** [comment]
Thank you for reporting, I'll check it at the weekend.

**Comment by adoeller** [comment]
Olive green also works nicely, thank you.
with the new option on, the transparancy is also good and one can see the details underneath it.
