### ISSUE TITLE
show cobbled streets in the map

### ISSUE THREAD

**Issue by adoeller** [TapioOfTapiola/oam_theme_tapiola#3]
Hi,
could you show the cobbled streets with a separate pattern?
the street NE and in the south are cobbled in this screen shot.

![Screenshot_2023-11-08-16-24-08-107_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/8ce4faba-8a8d-4d52-92c8-65249613b179)

**Comment by TapioOfTapiola** [comment]
Thx, will look at it.

**Comment by TapioOfTapiola** [comment]
In OAM it's surface:rough_paved.
Added it, please try https://github.com/TapioOfTapiola/oam_theme_tapiola/blob/main/Tapiola.xml

**Comment by adoeller** [comment]
Hi,
Thanks, it does not cover all of the rough or gravel roads of the referenz map, but it covers my usecase.
Zoom level also works well.

Thanks you,
Alex

**Comment by TapioOfTapiola** [comment]
> it does not cover all of the rough or gravel roads

I want it to be "perfect"... please provide me a lat, lon position so I can look at the exact road... Thx!

**Comment by TapioOfTapiola** [comment]
OK, got it. E.g. 53.55176,10.01942

This is paving_stones and considered more smooth. More comfortable to drive on. OAM has bundled this into "smooth_paved". Rather comfortable to drive on, with bike. I think those shouldn't be marked. 

`value="smooth_paved" equivalent-values="concrete:plates,concrete:lanes,paving_stones,paving_stones:30,paving_stones:20,bricks,cement,metal,wood`

**Comment by adoeller** [comment]
sounds great. i like the grey dots you introduces with the amendment.

**Comment by adoeller** [comment]
on the other side, cement,metal,wood are smoothish surfaces. my intention was to highlight only the rough ones. like
gravel
cobbled
pebblestone

paving_stones etc. are smooth enough imho.

**Comment by TapioOfTapiola** [comment]
Well, this is what I did. Did you find roughly paved surfaces which the theme doesn't treat right?

Meanwhile I found (I think) the smooth paved surface tags are not included into the OAM maps.

**Comment by TapioOfTapiola** [comment]
I think we leave it at that. Let me know if I can close the isdue.

**Comment by adoeller** [comment]
It's open android map with elements theme.

Works for me, merci
Alex
