### ISSUE TITLE
show path in different style and bridges with flat beginning/end

### ISSUE THREAD

**Issue by adoeller** [TapioOfTapiola/oam_theme_tapiola#4]
![Screenshot_2023-11-27-20-18-02-083_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/0e5b857f-36ca-455c-97c4-2a3ea1fba0cf)

![Screenshot_2023-11-27-20-21-25-156_menion android locus pro](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/eed8cc6b-e13e-4d04-a92f-3b5af06dde9d)

Hi, is it possbile to distinguish between footway and path and to show the bridges flat? atm short bridges look a little like saucages :|

I've done that in the xml hopefully at the right place ...

[Tapiola.zip](https://github.com/TapioOfTapiola/oam_theme_tapiola/files/13479333/Tapiola.zip)

**Comment by TapioOfTapiola** [comment]
I am undecided, it's a can of worms and complex chaos. See https://www.google.com/search?q=osm+footway+vs+path
https://gist.github.com/gravitystorm/ff5a6fdc695f08de1751

etc

**Comment by adoeller** [comment]
I can see what you mean. "path is only needed when footway, cycleway or bridleway are misleading". I saw these pathes going from the pavement to houses. they are almost everytime access restricticted and private. and they are no (public) footway, cycleway etc. its nice to see some smaller pathes in residential areas.

i see you switched the color grey and brown, which is even better now.

the bridges i checked are looking good now.
