### ISSUE TITLE
added german translation for 4 options

### ISSUE THREAD

**Issue by adoeller** [TapioOfTapiola/oam_theme_tapiola#5]
Hi,

i added the missing german translations.

![grafik](https://github.com/TapioOfTapiola/oam_theme_tapiola/assets/45470571/137a59f4-5b20-4467-be1f-4e58e3cf3670)
[Tapiola_de.zip](https://github.com/TapioOfTapiola/oam_theme_tapiola/files/13761653/Tapiola_de.zip)

**Comment by TapioOfTapiola** [comment]
Thank you, I am aware, DE was lacking, RU even more. I have included your changes into the latest xml.
