### ISSUE TITLE
Missing /symbols/s_survey_point.svg

### ISSUE THREAD

**Issue by nono303** [TapioOfTapiola/oam_theme_tapiola#8]
Hi @TapioOfTapiola 
Thx for adding /osmc/*.svg.

Still have one file missing when using with **mapsforgesrv**:
`Thread-0@XmlUtils:200 - invalid resource: /symbols/s_survey_point.svg`
I found `s_survey_point.svg` from https://tartamillo.org/tiramisu/ or `survey.svg` from https://voluntary.nichesite.org/downloads.html?i=1

**Comment by TapioOfTapiola** [comment]
Thx for letting me know, it's in now.
